plot = график
time_zone = часовая зона
time_zone__local =
    .hover = местное время
time_zone__utc =
    .hover = всемирное координированное время
legend = легенда
    .hover = отобразить легенду на графике
link_axis = синхронизация осей
    .hover = синхронизация по оси { $axis }
drag = перетакивание
    .hover = перетакивание вдоль оси { $axis }
scroll = прокрутка
    .hover = прокрутка вдоль осей x и y
zoom = масштабирование
    .hover = масштабирование по оси { $axis }
points = точки
points__radius =
    .hover = радиус точек
points__fill =
    .hover = заливка точек
points__color =
    .hover = цвет точек
resampling = редискретизация
resampling__enable = включить
    .hover = включить редискретизацию
every = каждый
    .hover = запуск следующего окна каждые n секунд
window_duration = протяженность окна
window_size = размер окна
window_size_description = длина окна
