plot = plot
time_zone = time zone
time_zone__local =
    .hover = local time
time_zone__utc =
    .hover = coordinated universal time
legend = legend
    .hover = display the plot legend
link_axis = link axis
    .hover = link along the { $axis }-axis
drag = drag
    .hover = drag along the { $axis }-axis
scroll = scroll
    .hover = scroll along the x-axis and y-axis
zoom = zoom
    .hover = zoom along the { $axis }-axis
points = points
points__radius =
    .hover = points radius
points__fill =
    .hover = fill points
points__color =
    .hover = points color
resampling = resampling
resampling__enable = enable
    .hover = enable resampling
every = every
    .hover = start a window at this interval, seconds
window_duration = window duration
window_size = window size
    .description = the length of the window