analog_turbidity_controller = Analog turbidity controller
    .abbreviation = ATUC
    .hover = Analog turbidity controller
digital_disolved_oxygen_controller = Digital disolved oxygen controller
    .abbreviation = DDOC
    .hover = Digital disolved oxygen controller
digital_disolved_oxygen_controller_concentration_channel = Concentration channel { $index }
    .abbreviation = C{ $index }
    .hover = Digital disolved oxygen controller, concentration channel { $index }
digital_disolved_oxygen_controller_temperature_channel = Temperature channel { $index }
    .abbreviation = T{ $index }
    .hover = Digital disolved oxygen controller, temperature channel { $index }
digital_disolved_oxygen_controller_voltage_channel = Voltage channel { $index }
    .abbreviation = V{ $index }
    .hover = Digital disolved oxygen controller, voltage channel { $index }
digital_temperature_controller = Digital temperature controller
    .abbreviation = DTEC
    .hover = Digital temperature controller

in_real_time = In real time
loaded_files = Files
    .hover = Loaded files
delete_all = Delete all

index = Index
identifier = Identifier
value = Value
timestamp = Timestamp

precision = Precision
properties = Properties
sticky_columns = Sticky columns

filter = Filter
filter-by-identifier = By identifier
    .hover = Filter by identifier
sort = Sort
sort_by_identifier = By identifier
    .hover = Sort by identifier
sort_by_timestamp = By timestamp
    .hover = Sort by timestamp
sort_by_value = By value
    .hover = Sort by value
order = Order
ascending_order = Ascending
    .hover = Ascending order
descending_order = Descending
    .hover = Descending order
browse = Browse
    .hover = Browse selected
temperature = Temperature
turbidity = Turbidity
plot = Plot
    .hover = View as plot
table = Table
    .hover = View as table

plot = Plot
    .hover = General plot settings
plot__drag = Drag
    .hover = Drag along the { $axis }-axis
plot__legend = Legend
    .hover = Display the plot legend
plot__link_axis = Link axis
    .hover = Link along the { $axis }-axis
plot__zoom = Zoom
    .hover = Zoom along the { $axis }-axis
plot__scroll = Scroll
    .hover = Scroll along the x-axis and y-axis

resampling = Resampling
resampling__mean = Mean
    .hover = Resampling by mean
resampling__median = Median
    .hover = Resampling by median
resampling__every = Every
    .hover = Start a window at this interval, seconds
resampling__period = Period
    .hover = Window duration, seconds

rolling = Rolling
rolling__mean = Mean
    .hover = Rolling by mean
rolling__median = Median
    .hover = Rolling by median
rolling__window_size = Window size
    .hover = The length of the window
rolling__window_size = Window size
    .hover = The length of the window
rolling__min_periods = Min periods
    .hover = Amount of elements in the window that should be filled before computing a result

source = Source
source__line = Line
    .hover = Source line
source__points = Points
    .hover = Source points
source__points_color =
    .hover = Source points color
source__points_fill =
    .hover = Fill source points
source__points_radius =
    .hover = Source points radius

time = Time
time_zone = Time zone
time_zone__local = Local
    .hover = Local time
time_zone__utc = UTC
    .hover = Coordinated universal time
