analog_turbidity_controller = Analog turbidity controller
    .abbreviation = ATUC
    .hover = Analog turbidity controller
digital_disolved_oxygen_controller = Digital disolved oxygen controller
    .abbreviation = DDOC
    .hover = Digital disolved oxygen controller
digital_disolved_oxygen_controller_concentration_channel = Concentration channel { $index }
    .abbreviation = C{ $index }
    .hover = Digital disolved oxygen controller, concentration channel { $index }
digital_disolved_oxygen_controller_temperature_channel = Temperature channel { $index }
    .abbreviation = T{ $index }
    .hover = Digital disolved oxygen controller, temperature channel { $index }
digital_disolved_oxygen_controller_voltage_channel = Voltage channel { $index }
    .abbreviation = V{ $index }
    .hover = Digital disolved oxygen controller, voltage channel { $index }
digital_temperature_controller = Digital temperature controller
    .abbreviation = DTEC
    .hover = Digital temperature controller

in_real_time = In real time
loaded_files = Files
    .hover = Loaded files
delete_all = Delete all

index = Index
identifier = Identifier
value = Value
timestamp = Timestamp

precision = Precision
properties = Properties
sticky_columns = Sticky columns

filter = Filter
filter-by-identifier = By identifier
    .hover = Filter by identifier
sort = Sort
sort_by_identifier = By identifier
    .hover = Sort by identifier
sort_by_timestamp = By timestamp
    .hover = Sort by timestamp
sort_by_value = By value
    .hover = Sort by value
order = Order
ascending_order = Ascending
    .hover = Ascending order
descending_order = Descending
    .hover = Descending order
browse = Browse
    .hover = Browse selected
temperature = Temperature
turbidity = Turbidity
plot = Plot
    .hover = View as plot
table = Table
    .hover = View as table

rolling = Rolling
time = Time
plot = Plot
time_zone = Time zone
time_zone__local = Local
    .hover = Local time
time_zone__utc = UTC
    .hover = Coordinated universal time
legend = Legend
    .hover = Display the plot legend
link_axis = Link axis
    .hover = Link along the { $axis }-axis
drag = Drag
    .hover = Drag along the { $axis }-axis
scroll = Scroll
    .hover = Scroll along the x-axis and y-axis
zoom = Zoom
    .hover = Zoom along the { $axis }-axis

source = Source
source_line = Line
    .hover = Source line
source_points = Points
    .hover = Source points
source_points_radius =
    .hover = Source points radius
source_points_fill =
    .hover = Fill source points
source_points_color =
    .hover = Source points color
resampling = Resampling
resampling_by_mean = Mean
    .hover = Resampling by mean
resampling_by_median = Median
    .hover = Resampling by median
resampling__enable = Enable
    .hover = Enable resampling
every = Every
    .hover = Start a window at this interval, seconds
window_duration = Window duration
window_size = Window size
    .description = The length of the window